server:
  port: 8088

spring:
  application:
    name: cetc36-demo

# Trace日志级别
cetc36:
  mossad:
   level: 3

## prometheus
management:
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: health,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  server:
    port: 36001

aws:
  accesskey: COywdXhgxQzHyFPVxOLQ
  secretkey: nlJuJCL0Zc2NHTFh0A3FortwvTWeDRHYwd2fNh9B
  endpoint: localhost:19001
  bucket:
    biz: load